use_frameworks!

platform :ios, '12.0'

# pod 'DevPod', :path => '../../DevPod'

target 'WolfNIO_Example' do
  pod 'WolfNIO', :path => '../'

  target 'WolfNIO_Tests' do
    inherit! :search_paths
  end
end
